### PR TITLE
chore: add arrow

### PR DESCRIPTION
**Pull request by eitsupi**

### CODE REVIEW

**Comment by wlandau-lilly** [comment]
Text file 'arrow' in pull request 193 has 6 lines. The file must have exactly 1 line unless it contains custom JSON (which is uncommon).

This pull request has been marked for manual review. Please either wait for an R-multiverse moderator to review, or close this pull request and open a different one which passes automated checks.

**Comment by wlandau** [comment]
R-multiverse currently in a testing/development stage where we are trying to host a small number of packages, so we are excluding most CRAN packages for the time being. Sorry about that.

**Comment by eitsupi** [comment]
Given that arrow was almost excluded from CRAN a few months ago and that there are currently problems with binary builds on CRAN, it is worth including here.

**Comment by eitsupi** [comment]
@wlandau @shikokuchuo Considering the importance of the arrow package, could you please rethink this?
Not long ago the <https://github.com/apache/arrow> repository did not create releases so the strategy of pinning in the R-universe did not work, but now I believe it does.

**Comment by shikokuchuo** [comment]
Thanks. We are definitely much further advanced now so I think the 'for the time being' no longer applies.
In any case, responding to a specific need from the community is in line with the project goals.

**Comment by eitsupi** [comment]
Thanks!

**Pull request merged**
